### PR TITLE
Add visibility extraction from CASA files and improved plotting

### PR DESCRIPTION
**Pull request by nkosogor**
@mbsherma @caseyjlaw 
Can you take a look at this?

Myles, I've tested all the shapes in the images we intend to send but haven't actually sent them yet. The shape is in the comments: https://github.com/dsa110/dsa110-nsfrb/blob/994e0f1f3e9c71cafe4acc4e7a5827f8828187aa/nsfrb/ms_vis_extraction.py#L116-L119
Can you check if it's working.

I've also moved all the plotting to a separate script.

### CODE REVIEW

**Comment by mbsherma** [comment]
@nkosogor Nice work, just 2 small adjustments: on line 115, you'll want the timestamp in 'isot' format instead of 'iso' (doesn't matter too much but the server is expecting 'isot' format). Then for the data shape on line 119, 'num_channels' is equal to 1 since it's just imaging 1 sub-band, right? Can you remove the 'num_channels' axis so the shape is (num_pix, num_pix, num_time_samples)? That's the format that send_data expects, but if it's too tricky I can just modify send_data instead.

**Comment by caseyjlaw** [comment]
Great stuff!
@mbsherma Github has a nice feature for commenting on individual lines. If you go under "files changed", you'll see the code and click on the plus symbol to comment.

**Comment by nkosogor** [comment]
Just to keep Casey updated: I've addressed the minor issues Myles mentioned. The images we create include all frequencies because the CASA files aggregate them. Following a discussion with Myles about testing the system, we are now sending each subband separately.

@mbsherma Can you try running it please?

**Comment by mbsherma** [comment]
Thanks for making these changes! I’ll test as soon as I can!

**Pull request merged**
