### PR TITLE
Commencing Offline System Tests

### PR DESCRIPTION
**Pull request by mbsherma**
This pull request covers the final changes made before visibility data began streaming to h24 for offline processing. This includes revision of noise estimation and injection code, re-ordering the search pipeline to minimize false positives, implementing shape-based clustering, and S/N threshold tuning. I've requested review from @nkosogor and @caseyjlaw but others feel free to take a look.

# Changes and Features Added

## Injections and Noise Estimation
- Simulated injections are now input at the UV gridding stage, with optional parameters passed to the `offline_imager` to control the position, S/N, DM, and width
- Noise is added to injections in visibilities instead of the image plane, making them more accurate to real bursts. Noise statistics have been re-estimated with this change using the `init_noise_from_fast_vis_UVW.py` script, and the `init_noise()` function modified to use the revised visibility plane noise estimates.
- options for false positive (`--fprtest`) and false negative (`--fnrtest`) were added to the process server to tune the S/N threshold with injection testing; the false positive rate is effectively 0% and S/N threshold for 50% false negative rate is ~6.5sigma

## Data Management and T4 Trigger
- The `nsfrb/T4` manager was added to trigger voltage dumps for candidates, modelled off of the T3 triggering system (https://github.com/dsa110/dsa110-T3)
- The `/dataz/` 60 TB RAID drive has been arranged to store fast visibilities, candidates, and injections. T4-triggered voltage dumps and visibilities for any candidates will be saved to `/dataz/`. 
- The `offline/clearvis.py` and `offline/clearcands.py` scripts run continuous data cleanup processes that clear raw candidates every 7 hours and visibilities every day (while testing with 2 channels/sub-band, visibilities need only be cleared weekly)

## Classifying, Clustering, and Searching
- The `--train` option was added to the process server to save candidates as a training set for the ML classifier. These can be labelled manually and used for re-training with real data if necessary.
- A spatial-based clustering method was added to precede hdbscan clustering (`psf_cluster()`) which uses the PSF shape to group candidates into possible point sources. This increases the total candidates to cluster, but results in fewer final clusters after hdbscan and fewer false positives.  
- Spatial filtering with the PSF was moved to the end of the search pipeline (now `dedispersion -- boxcar filtering -- PSF filtering`) to prevent artificial false positives from being introduced. This reduced the false positive rate from ~10% at 6sigma to 0%. 

## Bug Fixes
- A de-dispersion sign error was corrected
- A 180deg offset in azimuth direction of the DSA-110 was corrected

### CODE REVIEW

**Comment by caseyjlaw** [comment]
Some quick comments:
- it is difficult to review this well when it is large. good to develop "features" when possible. obviously nsfrb is complex and some initial work will require big commits.
- there are lots of small data files starting with `.`. Are they required?
- there are many `run_` functions in the manager modules. They are unused, if I understand what you are doing, so best to remove them.

**Comment by mbsherma** [comment]
@caseyjlaw Thanks for the comments:
- yes this pull request is too long, I had hoped to merge much earlier and will try to keep them to 10-20 commits in the future. 
- Can you point me to one of the data files you mean? I tried to remove any extra or temporary files but I'm not sure which ones you're referring to
- I kept all of the run functions for now because the T4 manager hasn't been tested yet. I'd like to leave them for now until we can test the triggering system and can be sure we don't need them or need to refer to them.

**Comment by caseyjlaw** [comment]
GitHub has a list of files changed. I see many binaries starting with ".".

**Comment by mbsherma** [comment]
Oh I see, they're from the simulations but there in a MAC cache directory I think. I will add that to the .gitignore and commit

**Comment by mbsherma** [comment]
@caseyjlaw https://github.com/dsa110/dsa110-nsfrb/pull/14#issuecomment-2480085698 resolved with commit https://github.com/dsa110/dsa110-nsfrb/pull/14/commits/b8cafe6c2dd6760f3da10ab6061995b1e298ad4b

**Comment by nkosogor** [comment]
Myles, this looks great! You’ve done lots of impressive development here! Below are a few suggestions and questions that might help refine the code further:

---

### Main README
- When installing, should we first create the environment using `conda env create -f casa10nsfrb_env.yml` (is this file `casa310nsfrb_env.yml` instead?) and then run `pip install .`? Should `casa38nsfrb_env.yml` be removed if it’s no longer needed?
- Adding a diagram of the pipeline and how the code interacts would be helpful. I recall you had great diagrams for the offline and online pipelines—could some of this be added to the README? A brief description of each module in the package would also improve clarity
- Since there are deprecated scripts, would it make sense to create a `legacy/` directory to store unused or older scripts, while also removing mentions of them in the README files?
- I suggest tagging the repository once the offline pipeline is fully verified, ensuring this version is saved

---

### `cand_cutter`
- Recommend removing commented-out code (e.g., [here](https://github.com/dsa110/dsa110-nsfrb/blob/6eb1bfbe427e2c1e2eaf503dd991cf4b7c127c94/cand_cutter/run.py#L186-L313)) unless it is explicitly needed for future reference
- In [cand_cutter/run.py](https://github.com/dsa110/dsa110-nsfrb/blob/development/cand_cutter/run.py), most arguments from `main` don’t seem to be used—could these be removed or documented further?
- Adding a README to the [cand_cutter directory](https://github.com/dsa110/dsa110-nsfrb/tree/development/cand_cutter), similar to other modules, would make it clearer
- Some files like `process_log.txt` in the cand_cutter directory are empty. Would it make sense to either remove these or replace them with example files containing useful information?

---

### `dsaT4`
- In [T4_manager.py](https://github.com/dsa110/dsa110-nsfrb/blob/development/dsaT4/T4_manager.py), many functions aren’t actively used in the pipeline. Should we consider moving these to a separate script or removing them if not needed?

---

### `inject`
- Is [injecting.py](https://github.com/dsa110/dsa110-nsfrb/blob/development/inject/injecting.py) an older version of [inject_burst_image.py](https://github.com/dsa110/dsa110-nsfrb/blob/development/inject/inject_burst_image.py)? If it’s not being used, would it make sense to remove it?

---

### `nsfrb`
- Is [calibration.py](https://github.com/dsa110/dsa110-nsfrb/blob/development/nsfrb/calibration.py) still needed? If not, we could remove it or move it to a legacy directory
- In [TXclient.py](https://github.com/dsa110/dsa110-nsfrb/blob/development/nsfrb/TXclient.py), the IP address definition could be moved to environment variables for better security
- For [candcutting.py](https://github.com/dsa110/dsa110-nsfrb/blob/development/nsfrb/candcutting.py), adding a short description in the module’s README and some inline documentation would make it clearer, especially since this code is critical for clustering and classification
- Is [pipeline.py](https://github.com/dsa110/dsa110-nsfrb/blob/development/nsfrb/pipeline.py) still used? 

---

### `process_server`
- Files like [process_flags.txt](https://github.com/dsa110/dsa110-nsfrb/blob/development/process_server/process_flags.txt) and [process_log.txt](https://github.com/dsa110/dsa110-nsfrb/blob/development/process_server/process_log.txt) appear empty. Should we remove these?

---

### `scripts`
- `.sh` files contain IP addresses; replacing these with environment variables would improve security.
- Updating the README in the scripts directory could clarify its purpose. Moving testing scripts to a `tests` directory and adding a dedicated `monitoring/` directory for monitoring-related scripts might organize things better

---

### `simulations and classifications`
- [generate_offset_source_images.py](https://github.com/dsa110/dsa110-nsfrb/blob/development/simulations_and_classifications/generate_offset_source_images.py) looks almost identical to [generate_source_images.py](https://github.com/dsa110/dsa110-nsfrb/blob/development/simulations_and_classifications/generate_source_images.py). Is it being used anywhere? 
---

### `tests`
- Making sure all tests run properly is important. Since clustering plays a big role in the pipeline, it would also be great to add some test cases for it

---

### Other Suggestions
- Several global variables like `cwd`, `cand_dir`, and `output_file` are reused across modules. Encapsulating these into a configuration object would improve maintainability and reduce side effects

---

These are just suggestions and I hope they’re helpful! Let me know if you have any questions or need clarification/help with those 😊

**Comment by mbsherma** [comment]
@nkosogor These are really helpful comments; I'm working on implementing them and will send a summary of new commits as soon as possible

**Comment by mbsherma** [comment]
@nkosogor @caseyjlaw I've addressed https://github.com/dsa110/dsa110-nsfrb/pull/14#issuecomment-2482107795 in the commits above; the following changes were made:
- A `legacy` directory was created to store deprecated but potentially useful code
- updated NSFRB pipeline diagrams were added to the README.md file
- All README files were updated and a new README was added to `candcutter`
- commented code was removed where possible
- empty files leftover from past implementations were removed
- deprecated `scripts` were moved to `legacy` and the scripts README clarified the purpose for the folder.
- `generate_src_images.py` was replaced by `generate_offset_src_images.py`, and the old code moved to `legacy`. The only difference is that the updated code uses `apply_phase_shift` to place offset injected sources from the image center.
- the environment variable $NSFRBIP was created to store the IP address for h24

A few things were not yet implemented as they require additional attention, but can be postponed until after the merge:
- a `monitoring` directory was not yet created; this is a good idea, but hopefully future monitoring will be done with grafana. So I'll wait until we've implemented a grafana dashboard to do this if its still necessary.
- `scripts` were not moved to `tests` because most of them were for iterative testing or calibration rather than unit testing. I've clarified in the README file that the `scripts` directory is meant for miscellaneous testing and calibration.
- a version tag will be added once we get through testing on real data
- as mentioned in https://github.com/dsa110/dsa110-nsfrb/pull/14#issuecomment-2480122543 , the `T4_manager` has not been tested; I'm keeping all extra functions and code until I've properly tested this and verified they are not needed.

Let me know if you have any other comments or feedback, thanks!

**Review by nkosogor — APPROVED** [review]
Looks great!

**Pull request merged**
