### PR TITLE
Upgrade to CUDA 12 and JAX Installation

### PR DESCRIPTION
**Pull request by mbsherma**
@nkosogor @caseyjlaw @cpviolator Please review the following pull request which should encapsulate the recent upgrades to CUDA and JAX.

# Changes and Features Added:

## GPU Acceleration:
- `PyTorch` was used to accelerate dedispersion and matched filtering search pipeline, with inspiration from https://github.com/nkosogor/PyTorchDedispersion .
- In order to install JAX to use for GPU acceleration, the CUDA installation on h24 was upgraded to version 12.0, and the CUDA driver was upgraded to version 525.85.12. These are the latest versions compatible with Ubuntu 18.04.
- JAX (see https://jax.readthedocs.io/en/latest/index.html) was installed in the `casa310nsfrb` environment. Initial implementations of the dedispersion and boxcar filtering pipelines were added which use the `jax.numpy` module and `Just-In-Time` compilation. The `nsfrb/jax_funcs.py` module was added to contain any `Just-In-Time` compiled functions.
- The `process_server` is now implemented as a "thread server", and will search images on a new thread rather than a new process. This is to accomodate JAX's incompatibility with `os.fork` and has negligible impact on execution time.

## Burst Injection
- The `inject/inject_burst_image.py` script was added for easier injection of simulated bursts.

## Correctness and Noise Statistics
- More rigorous analysis of the search pipeline was conducted and the dedispersion and matched filtering pipelines were fixed. The results are now more accurate, and `nan` and `inf` values should no longer appear in the outputs.
- Added `nsfrb/noise.py` to handle  noise statistics, and added infrastructure to use previous image data for dedispersion as discussed.

## Offline Pipeline
- Added `offline/getfastvis.py` to rsync fast visibilities from the correlator nodes and save to disk on h24

## Visualization, and Documentation, and Output
- Added functionality to send candidate plots to Slack
- Added binary plot to output of `scripts/get_status.sh` to show candidates in RA and DEC
- Updated `README.md` files and added new documentation for `offline` and `inject` modules
- Removed `candidates` and `tmpoutput` directories; these are now saved to external directories (not in the git repo) initialized in `setup.py`
- This pull request will begin the version history at `v0.1.0`

### CODE REVIEW

**Comment by rh-codebase** [comment]
any reason this repo doesn't have any versioning tags(at least none have been pushed)? It's unclear to me whether the CUDA upgrade was backward compatible with existing code. Semantic versioning can help others understand these types of changes.

-- rick

**Comment by mbsherma** [comment]
> any reason this repo doesn't have any versioning tags(at least none have been pushed)? It's unclear to me whether the CUDA upgrade was backward compatible with existing code. Semantic versioning can help others understand these types of changes.
> […](#)
> -- rick

@rh-codebase Good point; the nsfrb code hasn't been deployed yet, so that was the only reason not to include versioning, 
but it would be good to start for the reasons you mention. I will try using the `version.py` script to generate a version for this repo. As far as backward compatibility, the previous code used CUDA 11.1 and Python 3.8. The NSFRB search is the only module running on h24, but other DSA modules that rely on the `casa38` conda environment and CUDA 11.1 (like those on h23) will not be able to run on h24. Therefore I've saved the Python 3.8 conda environment in a yml file (`dsa110-nsfrb/casa38nsfrb_env.yml`) and installed CUDA 12.0 side-by-side with CUDA 11.1 so that we can revert to the previous installation if needed.

**Comment by rh-codebase** [comment]
Some groups will use a v0.x.x to convey not officially released and 'API's may change just because I didn't get coffee this morning'. Not hard and fast though. Will be good to keep track of how mananging Python Environments goes. More for dsa2k. Thanks for the details.

**Comment by mbsherma** [comment]
Added initial version 0.1.0 in commit https://github.com/dsa110/dsa110-nsfrb/pull/12/commits/0d89b78b4da94976bd92dcc858086219eb54aef1

**Review by nkosogor — APPROVED** [review]

**Pull request merged**
